### ISSUE TITLE
DofBot Sim2Real Error 

### ISSUE THREAD

**Issue by dBlitz** [j3soon/OmniIsaacGymEnvs-DofbotReacher#5]
I'm currently encountering some challenges with the sim2real transition. To provide a clearer picture of the issue, I've attached 3 videos that include demonstrations and a snapshot

I am receiving error messages when I switch Sim2Real to True and then run the Sim2real command. I would greatly appreciate your expertise in guiding me through a debugging process or providing any insights on potential solutions.

![Screenshot from 2023-12-07 18-02-42](https://github.com/j3soon/OmniIsaacGymEnvs-DofbotReacher/assets/1728575/e63bf6b7-7673-4b4f-bc5b-7e23edcad2c3)
https://github.com/j3soon/OmniIsaacGymEnvs-DofbotReacher/assets/1728575/c2ff81a4-07e4-4ad7-af1a-1df884d6ddc1
https://github.com/j3soon/OmniIsaacGymEnvs-DofbotReacher/assets/1728575/8614bc2e-31ed-4ed9-a994-0a29fd45fe06
https://github.com/j3soon/OmniIsaacGymEnvs-DofbotReacher/assets/1728575/e3a85944-c4de-46e3-af59-95c922ba8e1f

Thank you in advance for your time and assistance. Looking forward to your valuable input.

**Comment by j3soon** [comment]
Hi, nice to know that someone is trying out the Sim2Real feature!

I appreciate the detailed information. To summarize, the three videos demonstrates the following respectively:
1. The failure case where the sim2real flag is enabled.
2. The success case without enabling sim2real.
3. The realworld dofbot could be controlled (reset) by using the Jupyter Notebook.

<hr>

I would like to confirm some additional information for ease of debugging:
1. Which Isaac Sim version are you using? I think you are using Isaac Sim 2023.1.0?
2. In video 1 / screenshot, which command did you use? I believe you are running the following command:
   ```sh
   python omniisaacgymenvs/scripts/rlgames_train.py task=DofbotReacher test=True num_envs=1 checkpoint=./runs/DofbotReacher/nn/DofbotReacher.pth
   ```
3. In video 2, are you using the pre-trained checkpoint or your own trained model when running [the testing section](https://github.com/j3soon/OmniIsaacGymEnvs-DofbotReacher#testing) (without enabling sim2real)?
4. In video 3, are you using the jupyter notebook file in this repo, or the one provided by dofbot?
5. Is the dofbot and your PC (with name `eco`) in the same local network? What's their respective IP?

**Comment by dBlitz** [comment]
Hello, 

Thanks for getting back to me.

1. Using Isaac Sim 2023.10-hotfix
2. Yes correct 
3. Yes correct
4. Using jupyter notebook file in this repo
5. Yes correct same local network. IP for dofbot is 10.0.0.137

**Comment by j3soon** [comment]
Hi,

As mentioned in the README, the Sim2Real code has not been tested on Isaac Sim 2023 yet. The error message seems to be a bug caused by the transition from Isaac Sim 2022 to Isaac Sim 2023. To confirm this issue, I'll need to test the code on my end. Unfortunately, I'm currently attending a conference abroad and don't have access to a physical Dofbot.

You could either wait for my return in 2 weeks to continue debugging the Isaac 2023 version, or consider trying out the Isaac Sim 2022 version in [the isaac-sim-2022.1.1 branch](https://github.com/j3soon/OmniIsaacGymEnvs-DofbotReacher/tree/isaac-sim-2022.1.1). The Isaac Sim 2022 version has been tested thoroughly and I believe it should work well with your current setup.

**Comment by dBlitz** [comment]
Hey J3soon,

Thanks for getting back to me. You're right! Isaac Sim 2022.1.1 works great. 

The only issues I'm facing now have to do with connection between packages being sent. After awhile, 5-15 seconds the communication breaks down between computer and Dofbot. 

See pictures attached
![Screenshot from 2023-12-08 16-04-32](https://github.com/j3soon/OmniIsaacGymEnvs-DofbotReacher/assets/1728575/32293a04-5b46-4f6d-8f80-72e09a59c933)
![Screenshot from 2023-12-08 16-04-55](https://github.com/j3soon/OmniIsaacGymEnvs-DofbotReacher/assets/1728575/c20d68a1-b96a-4051-813e-e8077a81ef67)

It might be that running directly TCP is unreliable compared to ROS. Let me know if you ever gotten any similar problems where it works for 5-15 seconds and then stops, then maybe resumes for another 5-15 seconds and that's when the Jupyter Notebook breaks, then the computer is still trying to publish data.

**Comment by dBlitz** [comment]
That was the problem I got it working! I guessed I was confused with the ReadMe.

Thank you!!

**Comment by dBlitz** [comment]
I'm sure you're familiar with: https://github.com/NVIDIA-Omniverse/OmniIsaacGymEnvs/blob/main/docs/training_with_camera.md

As the next logical step. When do you think you'll get 2023 Isaac Sim working with Dofbot? I can then run with cameras and understand better current limitations and how I can potentially contribute.

**Comment by j3soon** [comment]
Hi,

I don't have access to a physical Dofbot now. However, I aim to begin investigating the issue within a few weeks.

I'll let you know when the issue is resolved.

Thanks!

**Comment by codetea-fly** [comment]
Hi,
i encountered the same problem. i think the cause is that the class omni.isaac.core.tasks.BaseTask in  isaac-sim 2023 does not have the attribute 'test' . So if you really want to run sim2Real with isaac-sim 2023, maybe you should modify the code to adapt the package in isaac-sim 2023, Or you can simply modify the code in line 104 , dofbot_reacher.py. Just delete the condition 'self.test and self.num_envs == 1' ( i encountered another problem says that RLTaskInterface has no attribute '_num_envs')

![image](https://github.com/j3soon/OmniIsaacGymEnvs-DofbotReacher/assets/172456361/05d77eb4-cca3-44aa-90d7-82ba9e1af5fe)
i can run this sim2Real demo with the modification above like this vedio. Hope it could help you ~ Thx


https://github.com/j3soon/OmniIsaacGymEnvs-DofbotReacher/assets/172456361/679a3403-14a1-4b92-bb92-543e2c2a81b3

**Comment by j3soon** [comment]
Hi @codetea-fly. Thanks for providing the bug fix!

Would you be interested in opening a PR? I'll be more than happy to merge your fix!

**Comment by codetea-fly** [comment]
Hi, 
Sure, but i have to say that it's just a workaround :)
